<a href="https://colab.research.google.com/github/gioievolemattia/biografy_bot/blob/main/esercizio_parsing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Installazione e importazione delle librerie

Questo notebook utilizza 3 nuove librerie.

Esaminiamole tutte:

**BeautifulSoup** è una libreria che ci permette di analizzare il codice HTML e XML. Fornisce strumenti per estrarre dati dalle pagine web analizzando e attraversando l'albero degli elementi HTML/XML.

**requests** è una libreria che ci permette di inviare richieste HTTP. Rende semplice l'invio di richieste GET, POST e di altri tipi di richieste ai server web. Permette di lavorare facilmente con i servizi web e le API.

**pandas** è una libreria che ci permette di lavorare con i dati. Fornisce comodi strumenti per analizzare, manipolare ed elaborare dati strutturati.

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
!pip install bs4
!pip install requests
!pip install pandas

Collecting bs4
  Downloading bs4-0.0.2-py2.py3-none-any.whl.metadata (411 bytes)
Requirement already satisfied: beautifulsoup4 in /usr/local/lib/python3.12/dist-packages (from bs4) (4.13.5)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.12/dist-packages (from beautifulsoup4->bs4) (2.8.3)
Requirement already satisfied: typing-extensions>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from beautifulsoup4->bs4) (4.15.0)
Downloading bs4-0.0.2-py2.py3-none-any.whl (1.2 kB)
Installing collected packages: bs4
Successfully installed bs4-0.0.2
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (2.32.4)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests) (3.13)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests) (2026.4.22)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [ ]:
import pandas as pd

df = pd.read_csv("./kodland_data.csv")
bho1 = df[df['course'] == 'Python Pro']['points'].sum()
print(f"La somma dei punti per il corso 'Python Pro' è: {bho1}")

FileNotFoundError: [Errno 2] No such file or directory: './kodland_data.csv'

In [ ]:
import requests
import pandas as pd
from bs4 import BeautifulSoup

url = 'https://www.greenme.it/'
headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) Chrome/91.0.4472.124 Safari/537.36'}

response = requests.get(url, headers=headers)
bs = BeautifulSoup(response.text, "lxml")

dict_news = {"link": [], "titolo": []}

articoli = bs.find_all('article')
print(len(articoli))

for art in articoli:
    link_tag = art.find('a', href=True)
    titolo_tag = art.find(['h2', 'h3'])

    if link_tag and titolo_tag:
        dict_news["link"].append(link_tag['href'])
        dict_news["titolo"].append(titolo_tag.get_text(strip=True))

df_news = pd.DataFrame(dict_news)
print(f"Articoli trovati: {len(df_news)}")
df_news.head()

80
Articoli trovati: 80

,link,titolo
0,https://www.greenme.it/pet/cani/beagle-di-ridg...,Missione compiuta! Liberati 1.500 Beagle di Ri...
1,https://www.greenme.it/viaggi/italia/primo-mag...,Primo maggio nei borghi: cinque mete lontane d...
2,https://www.greenme.it/animali/animali-selvati...,"Timmy, la megattera arenata, ora è su una chia..."
3,https://www.greenme.it/ambiente/natura/finalme...,Finalmente il Piano nazionale di Ripristino de...
4,https://www.greenme.it/esg/carne-latte-e-bugie...,"Carne, latte e bugie verdi: il 98% delle prome..."

In [ ]:
import requests
import pandas as pd
from bs4 import BeautifulSoup
url = 'https://www.greenme.it/'
headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) Chrome/91.0.4472.124 Safari/537.36'}
response = requests.get(url, headers=headers)
bs = BeautifulSoup(response.text, "lxml")
dict_news = {"link": [], "titolo": []}

articoli = bs.find_all('article')
for art in articoli:
    link_tag = art.find('a', href=True)
    titolo_tag = art.find(['h2', 'h3'])

    if link_tag and titolo_tag:
        dict_news["link"].append(link_tag['href'])
        dict_news["titolo"].append(titolo_tag.get_text(strip=True))

df_news = pd.DataFrame(dict_news)
print(f"Articoli trovati: {len(df_news)}")
df_news.head(30)

Articoli trovati: 80

,link,titolo
0,https://www.greenme.it/pet/cani/beagle-di-ridg...,Missione compiuta! Liberati 1.500 Beagle di Ri...
1,https://www.greenme.it/viaggi/italia/primo-mag...,Primo maggio nei borghi: cinque mete lontane d...
2,https://www.greenme.it/animali/animali-selvati...,"Timmy, la megattera arenata, ora è su una chia..."
3,https://www.greenme.it/ambiente/natura/finalme...,Finalmente il Piano nazionale di Ripristino de...
4,https://www.greenme.it/esg/carne-latte-e-bugie...,"Carne, latte e bugie verdi: il 98% delle prome..."
5,https://www.greenme.it/lifestyle/sai-cosa-comp...,"Pesticidi, PFAS e metalli pesanti negli assorb..."
6,https://www.greenme.it/ambiente/chernobyl-40-a...,"Chernobyl, 40 anni dopo: l’eredità del più gra..."
7,https://www.greenme.it/lifestyle/sai-cosa-comp...,Pasta dal colore giallo intenso? Ti spiego cos...
8,https://www.greenme.it/viaggi/italia/la-citta-...,L’incantevole città termale dimenticata della ...
9,https://www.greenme.it/viaggi/italia/questo-e-...,Questo è l’albero più grande d’Europa e veglia...
10,https://www.greenme.it/viaggi/italia/ho-percor...,Argine degli Angeli: ti racconto l’emozione un...
11,https://www.greenme.it/viaggi/italia/val-dorci...,"Non solo Montalcino e Montepulciano, ti porto ..."
12,https://www.greenme.it/energia/quando-il-fotov...,Quando il fotovoltaico porta cure e speranza: ...
13,https://www.greenme.it/energia/fotovoltaico-da...,Fotovoltaico da balcone nei supermercati? Pann...
14,https://www.greenme.it/energia/fotovoltaico-in...,Fotovoltaico integrato: ecco il pannello solar...
15,https://www.greenme.it/energia/gli-emirati-ara...,Gli Emirati Arabi Uniti lasciano l’OPEC: cosa ...
16,https://www.greenme.it/pet/cani/pensionato-vin...,Pensionato vince 92mila euro al SuperEnalotto ...
17,https://www.greenme.it/pet/cani/addio-galileo-...,"Addio a Galileo, è morto il cane da pet therap..."
18,https://www.greenme.it/pet/cani/beagle-di-ridg...,Missione compiuta! Liberati 1.500 Beagle di Ri...
19,https://www.greenme.it/pet/gatti/il-gatto-ti-s...,Il gatto ti segue anche in bagno? Non minimizz...
20,https://www.greenme.it/esg/tonno-in-scatola-e-...,Tonno in scatola e marchio MSC: quanto conta d...
21,https://www.greenme.it/esg/carne-latte-e-bugie...,"Carne, latte e bugie verdi: il 98% delle prome..."
22,https://www.greenme.it/esg/alluvioni-cyberatta...,"Alluvioni, cyberattacchi, blackout: ecco come ..."
23,https://www.greenme.it/esg/economia-circolare/...,Così la CO2 emessa dai rifiuti urbani si trasf...
24,https://www.greenme.it/lifestyle/costume-e-soc...,Li vediamo ogni giorno. Ma non li vediamo davvero
25,https://www.greenme.it/lifestyle/sai-cosa-comp...,Oscar dell’olio 2026: tutti i migliori oli ext...
26,https://www.greenme.it/author/germana-carillo/,"Libertà di stampa al minimo storico, l’Italia ..."
27,https://www.greenme.it/author/ilaria/,"Bir Tawil, la terra di nessuno tra miniere d’o..."
28,https://www.greenme.it/author/ilaria/,"Decreto lavoro, il “salario giusto” e quella b..."
29,https://www.greenme.it/author/riccardo/,L’era dei combustibili fossili sta per finire?...

In [ ]:
!pip3 install bs4

Collecting bs4
  Downloading bs4-0.0.2-py2.py3-none-any.whl.metadata (411 bytes)
Requirement already satisfied: beautifulsoup4 in /usr/local/lib/python3.12/dist-packages (from bs4) (4.13.5)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.12/dist-packages (from beautifulsoup4->bs4) (2.8.3)
Requirement already satisfied: typing-extensions>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from beautifulsoup4->bs4) (4.15.0)
Downloading bs4-0.0.2-py2.py3-none-any.whl (1.2 kB)
Installing collected packages: bs4
Successfully installed bs4-0.0.2

In [ ]:
import requests
import pandas as pd
from bs4 import BeautifulSoup

In [ ]:
url="https://www.greenme.it/"

In [ ]:
response=requests.get(url)
print(response)

<Response [200]>

In [ ]:
url="https://www.greenme.it/ha"

In [ ]:
response=requests.get(url)
print(response)

<Response [404]>

In [ ]:
dict_news = {"link": [], "titolo": [], "autore": [], "data": []}
url = 'https://www.greenme.it/'
response = requests.get(url)
bs = BeautifulSoup(response.text,"lxml")

temp = bs.find_all('a', 'image-wrapper')
for i in temp:
dict_news["link"].append(i.get('href'))
dict_news["titolo"].append(i.get('title'))

temp = bs.find_all('div', 'post-meta')
for i in temp:
dict_news["autore"].append(i.find('span','post-author'))
dict_news["data"].append(i.find('span','post-date'))


df_news = pd.DataFrame(dict_news, columns=["link", "titolo", "autore", "data"])

df_news

IndentationError: expected an indented block after 'for' statement on line 7 (3417864903.py, line 8)

In [ ]:
dict_news = {"link": [], "titolo": [], "autore": [], "data": []}
url = 'https://www.greenme.it/'
response = requests.get(url)
bs = BeautifulSoup(response.text,"lxml")

temp = bs.find_all('a', 'image-wrapper')
for i in temp:
  dict_news["link"].append(i.get('href'))
  dict_news["titolo"].append(i.get('title'))

temp = bs.find_all('div', 'post-meta')
for i in temp:
  dict_news["autore"].append(i.find('span','post-author'))
  dict_news["data"].append(i.find('span','post-date'))


df_news = pd.DataFrame(dict_news, columns=["link", "titolo", "autore", "data"])

df_news

Empty DataFrame
Columns: [link, titolo, autore, data]
Index: []

In [ ]:
dict_news = {"link": [], "titolo": []}
url = 'https://www.leoscienza.it/'
pages = ["ambiente", "lifestyle", "casa-e-giardino", "animali","salute-e-alimentazione","mobilita","viaggi","scienza-e-tecnologia"]
count = 1

for i in pages:
  response = requests.get(url + i + "/")
  bs = BeautifulSoup(response.text,"lxml")
  temp = bs.find_all('a', 'image-wrapper')
for i in temp:
  dict_news["link"].append(i.get('href'))
  dict_news["titolo"].append(i.get('title'))

df_news = pd.DataFrame(dict_news, columns=["link", "titolo",])
df_news.to_csv("./saved_data.csv", index=False)